#!/bin/bash

bat_discharge_icon() {
    if [[ "$1" -lt "10" ]]; then
        echo "󰁺"
    elif [[ "$1" -lt "20" ]]; then
        echo "󰁻"
    elif [[ "$1" -lt "30" ]]; then
        echo "󰁼"
    elif [[ "$1" -lt "40" ]]; then
        echo "󰁽" 
    elif [[ "$1" -lt "50" ]]; then
        echo "󰁾" 
    elif [[ "$1" -lt "60" ]]; then
        echo "󰁿" 
    elif [[ "$1" -lt "70" ]]; then
        echo "󰂀" 
    elif [[ "$1" -lt "80" ]]; then
        echo "󰂁" 
    elif [[ "$1" -lt "90" ]]; then
        echo "󰂂" 
    elif [[ "$1" -lt "100" ]]; then
        echo "󰁹"  
    fi
}

bat_charge_icon() {
    if [[ "$1" -lt "10" ]]; then
        echo "󰢜"
    elif [[ "$1" -lt "20" ]]; then
        echo "󰂆"
    elif [[ "$1" -lt "30" ]]; then
        echo "󰂇"
    elif [[ "$1" -lt "40" ]]; then
        echo "󰂈" 
    elif [[ "$1" -lt "50" ]]; then
        echo "󰢝" 
    elif [[ "$1" -lt "60" ]]; then
        echo "󰂉" 
    elif [[ "$1" -lt "70" ]]; then
        echo "󰢞" 
    elif [[ "$1" -lt "80" ]]; then
        echo "󰢞" 
    elif [[ "$1" -lt "90" ]]; then
        echo "󰂋" 
    elif [[ "$1" -lt "100" ]]; then
        echo "󰂅"  
    fi
}

bat_stat_icon() {
    case $1 in 
        "Charging")
            bat_charge_icon $2;;
        "Discharging")
            bat_discharge_icon $2;;
        "Full")
            echo "󱈏";;
        *)
            echo "󰂑"
    esac
}

bat_status=$(cat /sys/class/power_supply/BAT1/status)
bat_cap=$(cat /sys/class/power_supply/BAT1/capacity)	
bat_stat=$(bat_stat_icon $bat_status $bat_cap)

echo " $bat_stat $bat_cap%"



