[opener]
visual = [
	{ run = '$VISUAL "$@"', block = false, for = "unix", orphan = true },
	{ run = "%VISUAL% %*",  block = false, for = "windows", orphan = true },
]
[open]
append_rules = [
    { mime = "text/*", use = "visual" },
    { mime = "inode/directory", use = "visual" }
]

[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/vnd.rar",         run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/x-zstd",          run = "ouch" },
	{ mime = "application/zstd",            run = "ouch" },
	{ mime = "application/java-archive",    run = "ouch" },
]
