#!/bin/bash

# XA_WM_NAME
# xsetroot -name "thing"

day_str() {
	local num="$1" 
	if [[ $num == "1" ]]; then
	  echo "Monday"
	elif [[ $num == "2" ]]; then
	  echo "Tuesday"
	elif [[ $num == "3" ]]; then
	  echo "Wednesday"
	elif [[ $num == "4" ]]; then
	  echo "Thursday"
	elif [[ $num == "5" ]]; then
	  echo "Friday"
	elif [[ $num == "6" ]]; then
	  echo "Saturday"
	else
	  echo "Sunday"
	fi
}

batt_stat_str() {
	local status="$1"
	if [[ $status == "Charging" ]]; then
		echo "󰂄"
	elif [[ $status == "Discharging" ]]; then
		echo "󰁹"
	elif [[ $status == "Full" ]]; then
		echo "󰂏"
	else
		echo "What"	
	fi
}

while [ true ]
do
	sleep 1
	d=$(date '+%u')
	day=$(day_str $d)
	battery=$(cat /sys/class/power_supply/BAT1/capacity)
	bat_status=$(cat /sys/class/power_supply/BAT1/status)
	bat_stat=$(batt_stat_str $bat_status)
	TOTALDOWN=$(ifconfig wlp4s0| grep "RX packets" | awk {'print $6 $7'})
	TOTALUP=$(ifconfig wlp4s0| grep "TX packets" | awk {'print $6 $7'})
	dat=$(date '+%F')
	tim=$(date '+%H:%M:%S')
	xsetroot -name "[ 󰕒 $TOTALUP 󰇚 $TOTALDOWN I $bat_stat $battery% I $day I $dat I $tim ]"
done
