#!/bin/sh

setxkbmap -option ctrl:swapcaps

for id in $(xinput list | grep "pointer" | cut -d '=' -f 2 | cut -f 1); do xinput set-prop $id 'libinput Accel Profile Enabled' 0 1 0; done

xset mouse 0 0
